version: "3.8"

services:
  nginx:
    image: nginx:latest
    networks: 
      - traefik_proxy
    deploy:
      labels:
        # Enable Service discovery for Traefik
        - "traefik.enable=true"
        # Define the WHoami router rule
        - "traefik.http.routers.nginx.rule=Host(`www.chrismart.co.uk`)"
        # Expose Whoami on the HTTPS entrypoint
        - "traefik.http.routers.nginx.entrypoints=websecure"
        # Enable TLS
        - "traefik.http.routers.nginx.tls=true"
        # Expose the whoami port number to Traefik
        - traefik.http.services.nginx.loadbalancer.server.port=80

networks:
  traefik_proxy:
    external: true
