services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt_db"
      MYSQL_USER: "passbolt_user"
      MYSQL_PASSWORD: "cDCNz#eQ8pk4-KifUOIx719%BMVdGA"
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - passbolt

  passbolt:
    image: passbolt/passbolt:latest-ce-non-root
    #Alternatively you can use rootl:
    #image: passbolt/passbolt:latest-ce
    restart: unless-stopped
    depends_on:
      - db
    environment:
      APP_FULL_BASE_URL: https://vault.chrismart.co.uk
      DATASOURCES_DEFAULT_HOST: "db"
      DATASOURCES_DEFAULT_USERNAME: "passbolt_user"
      DATASOURCES_DEFAULT_PASSWORD: "cDCNz#eQ8pk4-KifUOIx719%BMVdGA"
      DATASOURCES_DEFAULT_DATABASE: "passbolt_db"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    networks: 
      - traefik_proxy
      - passbolt
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.passbolt.rule=Host(`vault.chrismart.co.uk`)"
        - "traefik.http.routers.passbolt.entrypoints=websecure"
        - "traefik.http.routers.passbolt.tls=true"
        - traefik.http.services.passbolt.loadbalancer.server.port=8080
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "db:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    ports:
      - 8080:8080
volumes:
  database_volume:
  gpg_volume:
  jwt_volume:

networks:
  passbolt:
  traefik_proxy:
    external: true
